# Generated by Django 5.2.14 on 2026-05-19 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="book_book_grades_9517f7_idx",
        ),
    ]
