# Generated by Django 5.2.14 on 2026-05-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_remove_book_book_book_grades_9517f7_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Genre",
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("order",),
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="categories",
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(
                related_name="books", to="book.genre", verbose_name="Genres"
            ),
        ),
    ]
