# Generated by Django 5.2.14 on 2026-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_plantoread"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="book_book_is_acti_cdc55d_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_book_publish_124b1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="book_book_feature_83a50b_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="featured_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="grades",
        ),
        migrations.AddField(
            model_name="book",
            name="mutolaa_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mutolaa ID"
            ),
        ),
    ]
