# Generated by Django 5.2.14 on 2026-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_remove_book_book_book_is_acti_cdc55d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="order",
        ),
        migrations.RemoveField(
            model_name="book",
            name="page_count",
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_year",
        ),
        migrations.AddField(
            model_name="genre",
            name="mutolaa_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mutolaa ID"
            ),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
