# Generated by Django 5.2.14 on 2026-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_remove_book_language_remove_book_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="mutolaa_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mutolaa ID"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="audiobook_duration",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Audiobook Duration"
            ),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="duration",
            field=models.FloatField(null=True, verbose_name="Duration (seconds)"),
        ),
    ]
