# Generated by Django 5.2.14 on 2026-06-06 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple choice"),
                            ("short_answer", "Short answer"),
                        ],
                        max_length=32,
                        verbose_name="Question type",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        help_text="Used only for short answer questions",
                        max_length=512,
                        verbose_name="Correct answer",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Assessment question",
                "verbose_name_plural": "Assessment questions",
            },
        ),
        migrations.CreateModel(
            name="AssessmentQuestionDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple choice"),
                            ("short_answer", "Short answer"),
                        ],
                        max_length=32,
                        verbose_name="Question type",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        help_text="How many questions of this type to pick randomly for each user",
                        verbose_name="Question count",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment question distribution",
                "verbose_name_plural": "Assessment question distributions",
            },
        ),
        migrations.CreateModel(
            name="MonthlyAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start time")),
                ("end_time", models.DateTimeField(verbose_name="End time")),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        help_text="Seconds allowed to complete the test",
                        verbose_name="Time limit (seconds)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly assessment",
                "verbose_name_plural": "Monthly assessments",
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "option_text",
                    models.CharField(max_length=512, verbose_name="Option text"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
            ],
            options={
                "verbose_name": "Question option",
                "verbose_name_plural": "Question options",
            },
        ),
        migrations.CreateModel(
            name="UserMonthlyAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "spent_time_ms",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Spent time (milliseconds)"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is completed"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total score (percent)",
                    ),
                ),
            ],
            options={
                "verbose_name": "User monthly assessment attempt",
                "verbose_name_plural": "User monthly assessment attempts",
            },
        ),
        migrations.CreateModel(
            name="UserQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "submitted_answer",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Submitted answer"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user submitted the answer or not",
                        verbose_name="Is submitted",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
            ],
            options={
                "verbose_name": "User question answer",
                "verbose_name_plural": "User question answers",
            },
        ),
    ]
