# Generated by Django 5.2.14 on 2026-06-06 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessment", "0001_initial"),
        ("competition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyassessment",
            name="month_grade",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_assessment",
                to="competition.competitionmonthgrade",
                verbose_name="Month grade",
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestiondistribution",
            name="monthly_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_distributions",
                to="assessment.monthlyassessment",
                verbose_name="Monthly assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="monthly_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.monthlyassessment",
                verbose_name="Monthly assessment",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assessment.assessmentquestion",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="usermonthlyassessmentattempt",
            name="monthly_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="assessment.monthlyassessment",
                verbose_name="Monthly assessment",
            ),
        ),
        migrations.AddField(
            model_name="usermonthlyassessmentattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_assessment_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="userquestionanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_answers",
                to="assessment.usermonthlyassessmentattempt",
                verbose_name="Attempt",
            ),
        ),
        migrations.AddField(
            model_name="userquestionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="assessment.assessmentquestion",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="userquestionanswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_answers",
                to="assessment.questionoption",
                verbose_name="Selected option",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentquestiondistribution",
            constraint=models.UniqueConstraint(
                fields=("monthly_assessment", "question_type"),
                name="unique_assessment_question_type_distribution",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="unique_correct_option_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermonthlyassessmentattempt",
            constraint=models.UniqueConstraint(
                fields=("monthly_assessment", "user"),
                name="unique_attempt_assessment_user",
            ),
        ),
    ]
