# Generated by Django 5.2.14 on 2026-06-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_question_answers",
                to="assessment.usermonthlyassessmentattempt",
                verbose_name="Attempt",
            ),
        ),
    ]
