# Generated by Django 5.2.14 on 2026-06-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0004_plantoread"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
            ],
            options={
                "verbose_name": "Competition season",
                "verbose_name_plural": "Competition seasons",
            },
        ),
        migrations.CreateModel(
            name="CompetitionMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("month_start", models.DateField(verbose_name="Month start")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="months",
                        to="competition.competitionseason",
                        verbose_name="Season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition month",
                "verbose_name_plural": "Competition months",
            },
        ),
        migrations.CreateModel(
            name="CompetitionMonthGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1_5", "1-5 sinf"),
                            ("6", "6-sinf"),
                            ("7", "7-sinf"),
                            ("8", "8-sinf"),
                            ("9", "9-sinf"),
                            ("10", "10-sinf"),
                            ("11", "11-sinf"),
                        ],
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True, to="book.book", verbose_name="Books"
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_grades",
                        to="competition.competitionmonth",
                        verbose_name="Month",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition month grade",
                "verbose_name_plural": "Competition month grades",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "grade"), name="unique_competition_month_grade"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="competitionmonth",
            constraint=models.UniqueConstraint(
                fields=("season", "month_start"),
                name="unique_competition_month_season_month",
            ),
        ),
    ]
