# Generated by Django 5.2.14 on 2026-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionseason",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AddConstraint(
            model_name="competitionseason",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="only_one_active_competition_season",
            ),
        ),
    ]
