# Generated by Django 5.2.14 on 2026-06-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_plantoread"),
        ("competition", "0002_competitionseason_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionmonthgrade",
            name="books",
        ),
        migrations.CreateModel(
            name="CompetitionMonthBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Is required"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_month_books",
                        to="book.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "month_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="competition.competitionmonthgrade",
                        verbose_name="Month grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition month book",
                "verbose_name_plural": "Competition month books",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month_grade", "book"),
                        name="unique_competition_month_book",
                    )
                ],
            },
        ),
    ]
