# Generated by Django 5.2.14 on 2026-06-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0004_plantoread"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1_5", "1-5 sinf"),
                            ("6", "6-sinf"),
                            ("7", "7-sinf"),
                            ("8", "8-sinf"),
                            ("9", "9-sinf"),
                            ("10", "10-sinf"),
                            ("11", "11-sinf"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        help_text="1 = January … 12 = December", verbose_name="Month"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                ("start_time", models.DateTimeField(verbose_name="Start time")),
                ("end_time", models.DateTimeField(verbose_name="End time")),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        help_text="Seconds allowed to complete the test",
                        verbose_name="Time limit (seconds)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monthly_tests",
                        to="book.book",
                        verbose_name="Books",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly test",
                "verbose_name_plural": "Monthly tests",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mc_questions",
                        to="contest.monthlytest",
                        verbose_name="Test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple choice question",
                "verbose_name_plural": "Multiple choice questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="A, B, C or D", max_length=5, verbose_name="Label"
                    ),
                ),
                ("content", models.CharField(max_length=512, verbose_name="Content")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="contest.multiplechoicequestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple choice question option",
                "verbose_name_plural": "Multiple choice question options",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ShortAnswerQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "answer",
                    models.CharField(
                        help_text="Expected correct answer text",
                        max_length=512,
                        verbose_name="Correct answer",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sa_questions",
                        to="contest.monthlytest",
                        verbose_name="Test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Short answer question",
                "verbose_name_plural": "Short answer questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserMonthlyTestParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "spent_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Actual seconds the user spent before submitting",
                        verbose_name="Spent time (seconds)",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is completed"),
                ),
                (
                    "mc_correct",
                    models.PositiveIntegerField(
                        default=0, verbose_name="MC correct answers"
                    ),
                ),
                (
                    "sa_correct",
                    models.PositiveIntegerField(
                        default=0, verbose_name="SA correct answers"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total score (percent)",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="contest.monthlytest",
                        verbose_name="Test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_test_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User monthly test participation",
                "verbose_name_plural": "User monthly test participations",
            },
        ),
        migrations.CreateModel(
            name="UserMultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mc_answers",
                        to="contest.usermonthlytestparticipation",
                        verbose_name="Participation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="contest.multiplechoicequestion",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_answers",
                        to="contest.multiplechoicequestionoption",
                        verbose_name="Selected option",
                    ),
                ),
            ],
            options={
                "verbose_name": "User MC answer",
                "verbose_name_plural": "User MC answers",
            },
        ),
        migrations.CreateModel(
            name="UserShortAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "user_answer",
                    models.CharField(max_length=512, verbose_name="User answer"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is correct"),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sa_answers",
                        to="contest.usermonthlytestparticipation",
                        verbose_name="Participation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="contest.shortanswerquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "User SA answer",
                "verbose_name_plural": "User SA answers",
            },
        ),
        migrations.AddIndex(
            model_name="monthlytest",
            index=models.Index(
                fields=["month", "year"], name="monthly_test_month_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlytest",
            index=models.Index(
                fields=["start_time", "end_time"], name="monthly_test_time_range_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlytest",
            constraint=models.UniqueConstraint(
                fields=("grade", "month", "year"),
                name="unique_monthly_test_grade_month_year",
            ),
        ),
        migrations.AddIndex(
            model_name="multiplechoicequestion",
            index=models.Index(
                fields=["test", "is_active"], name="mc_question_test_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="multiplechoicequestion",
            constraint=models.UniqueConstraint(
                fields=("test", "order"), name="unique_mc_question_test_order"
            ),
        ),
        migrations.AddIndex(
            model_name="multiplechoicequestionoption",
            index=models.Index(
                fields=["question", "is_correct"], name="mc_option_correct_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="multiplechoicequestionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "label"), name="unique_mc_option_question_label"
            ),
        ),
        migrations.AddIndex(
            model_name="shortanswerquestion",
            index=models.Index(
                fields=["test", "is_active"], name="sa_question_test_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shortanswerquestion",
            constraint=models.UniqueConstraint(
                fields=("test", "order"), name="unique_sa_question_test_order"
            ),
        ),
        migrations.AddIndex(
            model_name="usermonthlytestparticipation",
            index=models.Index(
                fields=["user", "is_completed"], name="participation_user_done_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermonthlytestparticipation",
            index=models.Index(
                fields=["test", "is_completed"], name="participation_test_done_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermonthlytestparticipation",
            index=models.Index(fields=["total_score"], name="participation_score_idx"),
        ),
        migrations.AddConstraint(
            model_name="usermonthlytestparticipation",
            constraint=models.UniqueConstraint(
                fields=("test", "user"), name="unique_participation_test_user"
            ),
        ),
        migrations.AddIndex(
            model_name="usermultiplechoiceanswer",
            index=models.Index(
                fields=["participation", "is_correct"], name="mc_answer_correct_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usermultiplechoiceanswer",
            constraint=models.UniqueConstraint(
                fields=("participation", "question"),
                name="unique_mc_answer_participation_question",
            ),
        ),
        migrations.AddIndex(
            model_name="usershortanswer",
            index=models.Index(
                fields=["participation", "is_correct"], name="sa_answer_correct_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usershortanswer",
            constraint=models.UniqueConstraint(
                fields=("participation", "question"),
                name="unique_sa_answer_participation_question",
            ),
        ),
    ]
