# Generated by Django 5.2.14 on 2026-05-19 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_school"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrontendTranslation",
        ),
        migrations.DeleteModel(
            name="VersionHistory",
        ),
    ]
