# Generated by Django 5.2.14 on 2026-05-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_school"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="common.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identity_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Identity number"
            ),
        ),
    ]
