# Generated by Django 5.2.14 on 2026-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("phone_number", "identity_number")},
        ),
    ]
