# Generated by Django 5.2.14 on 2026-05-09 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="district",
        ),
    ]
